import React from 'react';
import {
  ACApplianceCardVisual,
  WashingMachineVisual,
  RefrigeratorVisual,
  TelevisionVisual,
  ChimneyVisual,
  MicrowaveVisual,
  StoveVisual,
  LaptopVisual,
  ROWaterPurifierVisual,
  GeyserVisual,
  AirCoolerVisual,
} from './ApplianceVisuals';

export interface ApplianceRepairItem {
  id: string;
  title: string;
  rating: number;
  reviewsCount: string;
  price: number;
  originalPrice: number;
  discountPercentage?: number;
  duration: string;
  warranty: string;
  description: string;
  includedPoints: string[];
  popular?: boolean;
  symptomTags: string[];
  image: string;
}

export interface ApplianceConfig {
  id: string;
  label: string;
  group: 'large' | 'other';
  title: string;
  subtitle: string;
  eta: string;
  rating: number;
  totalBookings: string;
  warrantyBadge: string;
  visualComponent: React.ComponentType<{ className?: string }>;
  commonIssues: string[];
  services: ApplianceRepairItem[];
  technicianChecklist: string[];
}

export const APPLIANCES_LIST: ApplianceConfig[] = [
  // 1. AC
  {
    id: 'ac',
    label: 'AC',
    group: 'large',
    title: 'AC Service & Repair',
    subtitle: 'Power foam jet deep cleaning, gas leak detection, inverter PCB fix & installation',
    eta: '44 mins',
    rating: 4.88,
    totalBookings: '2.4M bookings',
    warrantyBadge: '30-Day Happiness Guarantee',
    visualComponent: ACApplianceCardVisual,
    commonIssues: [
      'Not cooling / low airflow',
      'Water leakage from indoor unit',
      'Strange noise or odor',
      'Gas refill required',
      'Tripping MCB / Power issue',
    ],
    technicianChecklist: [
      'High-pressure power foam jet cleaning',
      'Electronic nitrogen gas leak sniffer test',
      'Zero-mess indoor waterproof apron jacket',
      'Accurate digital clamp meter amp draw check',
      '100% genuine factory refrigerant gas',
    ],
    services: [
      {
        id: 'ac-power-foam-jet-service',
        title: 'Power Foam Jet AC Service (Split)',
        rating: 4.89,
        reviewsCount: '840K',
        price: 599,
        originalPrice: 899,
        discountPercentage: 33,
        duration: '45 mins',
        warranty: '30 days warranty',
        description: 'Deep high-pressure anti-bacterial foam jet wash of cooling coils, blower fan and drain tray to restore 2x cooling efficiency.',
        includedPoints: [
          'Coil cleaning with eco-friendly foaming chemical',
          'Blower wheel and indoor drain pipe flushing',
          'Outdoor condenser high-velocity jet wash',
          'Pre & post cooling temperature check',
        ],
        popular: true,
        symptomTags: ['Not cooling / low airflow', 'Strange noise or odor'],
        image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'ac-gas-leak-and-refill',
        title: 'AC Gas Leak Repair & Pure Refill',
        rating: 4.86,
        reviewsCount: '320K',
        price: 2199,
        originalPrice: 2899,
        discountPercentage: 24,
        duration: '60 mins',
        warranty: '60 days leak warranty',
        description: 'Complete nitrogen pressure test to pinpoint copper coil pinhole leaks, gas brazing sealing, and weight-based pure refrigerant charging.',
        includedPoints: [
          'High pressure nitrogen sniffer leak test',
          'Copper tubing brazing & valve replacement',
          'Vacuum pump moisture evacuation',
          'Precision digital scale refrigerant refill (R32 / R410A)',
        ],
        popular: true,
        symptomTags: ['Gas refill required', 'Not cooling / low airflow'],
        image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'ac-water-leak-repair',
        title: 'Indoor Unit Water Drop & Drainage Fix',
        rating: 4.85,
        reviewsCount: '190K',
        price: 399,
        originalPrice: 599,
        discountPercentage: 33,
        duration: '35 mins',
        warranty: '30 days warranty',
        description: 'Clear sludge blockage in condensation drain pipe, level the mounting bracket and seal indoor unit drip tray cracks.',
        includedPoints: [
          'Drain pan ultrasonic descaling & clearing',
          'Condensate pipe vacuum blast',
          'Unit slope leveling to prevent backflow',
          'Anti-fungal drain tray disinfection',
        ],
        popular: false,
        symptomTags: ['Water leakage from indoor unit'],
        image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'ac-inverter-pcb-repair',
        title: 'Inverter Motherboard & PCB Diagnostics',
        rating: 4.82,
        reviewsCount: '140K',
        price: 999,
        originalPrice: 1499,
        discountPercentage: 33,
        duration: '60 mins',
        warranty: '90 days PCB warranty',
        description: 'Troubleshoot blinking LED error codes (E1, E6, F3), repair capacitor/transistor circuitry or replace sensor harnesses.',
        includedPoints: [
          'Micro-controller multimeter diagnostic',
          'Comm wire signal verification between indoor & outdoor',
          'Outdoor fan relay replacement if damaged',
          'Original OEM parts with 90-day guarantee',
        ],
        popular: false,
        symptomTags: ['Tripping MCB / Power issue', 'Strange noise or odor'],
        image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },

  // 2. Washing Machine
  {
    id: 'washing-machine',
    label: 'Washing Machine',
    group: 'large',
    title: 'Washing Machine Repair & Service',
    subtitle: 'Front load & top load drum balancing, drainage pump fix, spin motor & PCB repair',
    eta: '45 mins',
    rating: 4.87,
    totalBookings: '1.8M bookings',
    warrantyBadge: '90-Day Spare Parts Guarantee',
    visualComponent: WashingMachineVisual,
    commonIssues: [
      'Drum not spinning / vibrating loudly',
      'Water not draining or leaking',
      'Machine not powering on / Error codes (OE, dE, 4E)',
      'Water not filling / slow inlet',
      'Bad odor / clothes not cleaned properly',
    ],
    technicianChecklist: [
      'Digital tachometer spin rate diagnostic',
      'Inlet solenoid valve pressure test',
      'Shock absorber and suspension spring audit',
      'Drainage coin trap and lint filter unclogging',
      'Zero mess floor mat protection during repairs',
    ],
    services: [
      {
        id: 'wm-full-checkup-diagnostics',
        title: 'Washing Machine Complete Checkup & Diagnosis',
        rating: 4.88,
        reviewsCount: '490K',
        price: 299,
        originalPrice: 499,
        discountPercentage: 40,
        duration: '30 mins',
        warranty: '30 days warranty',
        description: 'Comprehensive 24-point electrical and mechanical diagnostic for Front Load, Top Load, and Semi-Automatic machines.',
        includedPoints: [
          'Drum spider & bearing health inspection',
          'Water pressure sensor & solenoid valve check',
          'Drain pump impeller and belt tension test',
          'Inspection fee adjusted against repair bill',
        ],
        popular: true,
        symptomTags: ['Drum not spinning / vibrating loudly', 'Machine not powering on / Error codes (OE, dE, 4E)'],
        image: 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'wm-drum-bearing-suspension',
        title: 'Drum Spin & Heavy Vibration Repair',
        rating: 4.86,
        reviewsCount: '210K',
        price: 699,
        originalPrice: 999,
        discountPercentage: 30,
        duration: '60 mins',
        warranty: '90 days warranty',
        description: 'Fix heavy shaking, thumping noises during spin cycle by replacing worn damper shocks, suspension rods or drum bearings.',
        includedPoints: [
          'Heavy duty hydraulic shock absorber replacement',
          'Drum balance calibration and spider shaft inspection',
          'Motor drive belt tension adjustment',
          '100% genuine damper mounts',
        ],
        popular: true,
        symptomTags: ['Drum not spinning / vibrating loudly'],
        image: 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'wm-water-drain-pump-fix',
        title: 'Drain Pump & Water Inlet Valve Repair',
        rating: 4.85,
        reviewsCount: '175K',
        price: 549,
        originalPrice: 799,
        discountPercentage: 31,
        duration: '40 mins',
        warranty: '90 days warranty',
        description: 'Solve standing water inside drum, slow water intake, or leaking bottom hose gaskets.',
        includedPoints: [
          'Drain motor impeller replacement / foreign coin removal',
          'Dual solenoid inlet valve cleaning or replacement',
          'Hose clamp tightening and leak prevention',
          'Complete wash-rinse cycle water flow test',
        ],
        popular: false,
        symptomTags: ['Water not draining or leaking', 'Water not filling / slow inlet'],
        image: 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'wm-deep-tub-descaling-clean',
        title: 'Deep Tub Scale & Sludge Chemical Wash',
        rating: 4.9,
        reviewsCount: '310K',
        price: 499,
        originalPrice: 749,
        discountPercentage: 33,
        duration: '50 mins',
        warranty: '100% Fresh Odor Guarantee',
        description: 'Dismantle outer pulsator plate and blast hidden bacteria, detergent scum and hard water calcium deposits.',
        includedPoints: [
          'Caustic-free high performance tub descaling chemical',
          'Pulsator removal and high pressure water scrub',
          'Door rubber gasket mold and mildew removal',
          'Lint trap and water filter sterilization',
        ],
        popular: true,
        symptomTags: ['Bad odor / clothes not cleaned properly'],
        image: 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },

  // 3. Refrigerator
  {
    id: 'refrigerator',
    label: 'Refrigerator',
    group: 'large',
    title: 'Refrigerator Repair & Gas Refill',
    subtitle: 'Single door, double door & side-by-side inverter fridge diagnostics, cooling coil & compressor fix',
    eta: '45 mins',
    rating: 4.89,
    totalBookings: '1.4M bookings',
    warrantyBadge: '180-Day Compressor Warranty',
    visualComponent: RefrigeratorVisual,
    commonIssues: [
      'Freezer working but lower fridge not cooling',
      'No cooling at all / Compressor not humming',
      'Water pooling under crisper box',
      'Excess ice buildup in freezer',
      'Door rubber seal gasket loose',
    ],
    technicianChecklist: [
      'Infrared laser thermometer temperature map',
      'Compressor relay & OLP resistance testing',
      'Defrost timer & bimetal thermal fuse validation',
      'Eco-friendly R600a/R134a precision gas charging',
      'Magnetic door gasket vacuum seal check',
    ],
    services: [
      {
        id: 'fridge-checkup-diagnostics',
        title: 'Refrigerator Expert Inspection & Diagnosis',
        rating: 4.88,
        reviewsCount: '380K',
        price: 299,
        originalPrice: 499,
        discountPercentage: 40,
        duration: '30 mins',
        warranty: '30 days warranty',
        description: 'Complete inspection of compressor starting relay, thermostat, capillary tube and evaporator cooling coils.',
        includedPoints: [
          'Thermostat and temperature sensor test',
          'Compressor starting capacitor and relay audit',
          'Defrost heater and evaporator fan motor check',
          'Inspection fee adjusted against repair bill',
        ],
        popular: true,
        symptomTags: ['No cooling at all / Compressor not humming', 'Freezer working but lower fridge not cooling'],
        image: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'fridge-defrost-cooling-coil-fix',
        title: 'Frost-Free Defrost & Fan Motor Repair',
        rating: 4.87,
        reviewsCount: '190K',
        price: 649,
        originalPrice: 949,
        discountPercentage: 32,
        duration: '50 mins',
        warranty: '90 days warranty',
        description: 'Resolves heavy ice choking the cooling coil causing warm bottom compartments in double door fridges.',
        includedPoints: [
          'Bimetal thermal fuse & defrost timer replacement',
          'Evaporator circulation fan motor repair',
          'Drain chute heating and unblocking',
          'Air damper flap airflow calibration',
        ],
        popular: true,
        symptomTags: ['Freezer working but lower fridge not cooling', 'Excess ice buildup in freezer'],
        image: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'fridge-gas-refill-compressor',
        title: 'Compressor & Refrigerant Gas Charging',
        rating: 4.84,
        reviewsCount: '150K',
        price: 1899,
        originalPrice: 2499,
        discountPercentage: 24,
        duration: '70 mins',
        warranty: '180 days warranty',
        description: 'Pinpoint copper capillary leaks, change filter drier and recharge genuine R600a/R134a refrigerant.',
        includedPoints: [
          'Nitrogen pressure leak detection',
          'Hermetic copper tube brazing and seal',
          'New molecular sieve filter drier installation',
          'Pure hydrocarbon refrigerant weigh-in charging',
        ],
        popular: false,
        symptomTags: ['No cooling at all / Compressor not humming'],
        image: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'fridge-door-gasket-replacement',
        title: 'Magnetic Door Gasket Seal Replacement',
        rating: 4.86,
        reviewsCount: '110K',
        price: 599,
        originalPrice: 849,
        discountPercentage: 29,
        duration: '40 mins',
        warranty: '90 days warranty',
        description: 'Replace worn, torn or hardened magnetic rubber door seal to stop cool air leakage and compressor overdrive.',
        includedPoints: [
          'Custom brand fit food-grade antibacterial rubber seal',
          'Four-corner airtight vacuum alignment',
          'Eliminates moisture droplet buildup on shelves',
        ],
        popular: false,
        symptomTags: ['Door rubber seal gasket loose', 'Water pooling under crisper box'],
        image: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },

  // 4. Television
  {
    id: 'television',
    label: 'Television',
    group: 'large',
    title: 'Television Repair & Installation',
    subtitle: 'LED / OLED / QLED TV screen backlight repair, motherboard PCB fix, wall mounting & audio diagnostics',
    eta: '50 mins',
    rating: 4.86,
    totalBookings: '950K bookings',
    warrantyBadge: '90-Day Screen & Board Guarantee',
    visualComponent: TelevisionVisual,
    commonIssues: [
      'Sound is clear but screen is completely black',
      'TV not turning on / red standby light blinking',
      'Horizontal or vertical lines on display',
      'Wall mounting & concealment installation',
      'HDMI port / Wi-Fi smart connectivity issue',
    ],
    technicianChecklist: [
      'Precision optical backlight LED tester',
      'Oscilloscope T-Con board timing signal test',
      'Heavy duty swivel wall bracket anchor test',
      'Anti-static wrist strap ESD safe handling',
      'Zero display scratch protective cushion mat',
    ],
    services: [
      {
        id: 'tv-backlight-strip-replacement',
        title: 'LED Backlight Strip Replacement (Black Screen Fix)',
        rating: 4.89,
        reviewsCount: '270K',
        price: 1299,
        originalPrice: 1899,
        discountPercentage: 31,
        duration: '60 mins',
        warranty: '90 days warranty',
        description: 'Fixes TVs where audio plays normally but screen remains pitch dark due to burned internal LED lens strips.',
        includedPoints: [
          'Uniform aluminum core high-lumen LED strip array',
          'Optical lens diffuser alignment for zero dark spots',
          'Current limiter tuning to prevent future burnouts',
          'Safe cleanroom display layer re-lamination',
        ],
        popular: true,
        symptomTags: ['Sound is clear but screen is completely black'],
        image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'tv-wall-mounting-installation',
        title: 'TV Wall Mounting & Bracket Installation',
        rating: 4.92,
        reviewsCount: '410K',
        price: 349,
        originalPrice: 599,
        discountPercentage: 41,
        duration: '35 mins',
        warranty: '1-Year Mount Security Guarantee',
        description: 'Heavy duty steel wall mount installation (32" to 75"+) with laser spirit leveling and neat cable bundling.',
        includedPoints: [
          'High load anchor bolts suitable for brick and concrete',
          'Precise eye-level laser alignment',
          'AV/HDMI cable organization and wire trunking',
          'Full swivel / tilt bracket setup support',
        ],
        popular: true,
        symptomTags: ['Wall mounting & concealment installation'],
        image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'tv-motherboard-power-pcb-fix',
        title: 'Power Supply Board & Motherboard Diagnostics',
        rating: 4.83,
        reviewsCount: '160K',
        price: 899,
        originalPrice: 1299,
        discountPercentage: 30,
        duration: '50 mins',
        warranty: '90 days warranty',
        description: 'Repair capacitor blowouts, dead power supplies, standby blink loop, or fried HDMI input ports.',
        includedPoints: [
          'SMD component level multimeter troubleshooting',
          'High voltage regulator and diode replacement',
          'Firmware eMMC chip reflashing',
          'Original OEM motherboard board match',
        ],
        popular: false,
        symptomTags: ['TV not turning on / red standby light blinking', 'HDMI port / Wi-Fi smart connectivity issue'],
        image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },

  // 5. Chimney
  {
    id: 'chimney',
    label: 'Chimney',
    group: 'other',
    title: 'Kitchen Chimney Service & Degreasing',
    subtitle: 'Baffle filter caustic degreasing, motor suction tuning, ducting pipe replacement & repair',
    eta: '50 mins',
    rating: 4.87,
    totalBookings: '820K bookings',
    warrantyBadge: '30-Day Oil-Free Guarantee',
    visualComponent: ChimneyVisual,
    commonIssues: [
      'Low suction / kitchen gets smoky',
      'Heavy sticky oil dripping from filters',
      'Loud humming / rattling motor noise',
      'Touch / gesture control panel not responding',
      'Duct pipe torn or loose',
    ],
    technicianChecklist: [
      'Eco-friendly deep caustic degreasing bath',
      'Air velocity anemometer suction test',
      'Blower rotor dynamic wheel balance check',
      'Zero oil splash stove & countertop protective film',
      'Duct pipe leak-proof aluminum foil tape sealing',
    ],
    services: [
      {
        id: 'chimney-deep-degreasing-service',
        title: 'Deep Dismantle Chemical Degreasing Service',
        rating: 4.9,
        reviewsCount: '410K',
        price: 499,
        originalPrice: 799,
        discountPercentage: 37,
        duration: '50 mins',
        warranty: '30 days warranty',
        description: 'Complete dismantling of baffle filters, oil collector cup and motor blower chamber soaked in warm degreasing dip.',
        includedPoints: [
          'Baffle filter ultrasonic and hot caustic grease removal',
          'Blower fan wheel scrub and carbon removal',
          'Stainless steel outer canopy mirror buffing',
          'Suction restoration to factory spec (1200+ m3/hr)',
        ],
        popular: true,
        symptomTags: ['Heavy sticky oil dripping from filters', 'Low suction / kitchen gets smoky'],
        image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'chimney-motor-noise-suction-fix',
        title: 'Chimney Motor Noise & Rotor Repair',
        rating: 4.85,
        reviewsCount: '190K',
        price: 699,
        originalPrice: 999,
        discountPercentage: 30,
        duration: '55 mins',
        warranty: '90 days warranty',
        description: 'Fix annoying humming or vibration by replacing worn motor bush bearings or aligning uncentered fan rotors.',
        includedPoints: [
          'Copper winding stator health diagnostic',
          'Vibration-damping silicone grommet install',
          'Impeller wheel realignment',
          'Capacitor tuning for instant speed ramping',
        ],
        popular: false,
        symptomTags: ['Loud humming / rattling motor noise', 'Low suction / kitchen gets smoky'],
        image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'chimney-ducting-pipe-installation',
        title: 'Flexible Aluminum Ducting Pipe Replacement',
        rating: 4.88,
        reviewsCount: '140K',
        price: 549,
        originalPrice: 799,
        discountPercentage: 31,
        duration: '40 mins',
        warranty: '1-Year Duct Security Guarantee',
        description: 'Replace torn or leaking plastic pipes with heavy duty expandable corrugated aluminum duct and outer bird guard cowl.',
        includedPoints: [
          'Expandable 10-foot tear-resistant aluminum pipe',
          'High strength stainless steel hose jubilee clamps',
          'Outer wall exhaust gravity flap louvers to prevent pests',
        ],
        popular: true,
        symptomTags: ['Duct pipe torn or loose'],
        image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },

  // 6. Microwave
  {
    id: 'microwave',
    label: 'Microwave',
    group: 'other',
    title: 'Microwave Oven Repair & Service',
    subtitle: 'Solo, grill & convection microwave magnetron repair, turntable motor fix & keypad replacement',
    eta: '45 mins',
    rating: 4.85,
    totalBookings: '620K bookings',
    warrantyBadge: '90-Day Magnetron Guarantee',
    visualComponent: MicrowaveVisual,
    commonIssues: [
      'Oven runs but food does not heat up',
      'Sparks / crackling noise inside cavity',
      'Turntable glass plate not rotating',
      'Touchpad buttons not responding',
      'Burning smell or smoke',
    ],
    technicianChecklist: [
      'High-voltage capacitor safety discharge',
      'Microwave radiation leakage survey meter check',
      'Magnetron filament resistance test',
      'Mica waveguide cover plate replacement',
      'Cavity sanitization and door interlock safety test',
    ],
    services: [
      {
        id: 'micro-magnetron-heating-repair',
        title: 'Not Heating Magnetron & High Voltage Diode Fix',
        rating: 4.88,
        reviewsCount: '230K',
        price: 799,
        originalPrice: 1199,
        discountPercentage: 33,
        duration: '45 mins',
        warranty: '90 days warranty',
        description: 'Resolves the most common microwave issue where fan and lights operate but dishes remain stone cold.',
        includedPoints: [
          'Genuine OEM magnetron tube replacement',
          'High voltage transformer & diode continuity check',
          'Safety door switch interlock test',
          'Full heating load beaker water test',
        ],
        popular: true,
        symptomTags: ['Oven runs but food does not heat up'],
        image: 'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'micro-spark-mica-plate-service',
        title: 'Sparking Fix & Mica Waveguide Plate Replacement',
        rating: 4.86,
        reviewsCount: '150K',
        price: 349,
        originalPrice: 499,
        discountPercentage: 30,
        duration: '30 mins',
        warranty: '60 days warranty',
        description: 'Stops hazardous electric arcing caused by burnt or grease-soaked mica sheet inside the inner chamber.',
        includedPoints: [
          'High grade silver-mica insulator plate installation',
          'Cavity carbon soot removal and enamel repaint',
          'Eliminates fire hazards and popping sparks',
        ],
        popular: true,
        symptomTags: ['Sparks / crackling noise inside cavity', 'Burning smell or smoke'],
        image: 'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'micro-turntable-motor-roller-fix',
        title: 'Turntable Motor & Roller Ring Replacement',
        rating: 4.83,
        reviewsCount: '110K',
        price: 399,
        originalPrice: 599,
        discountPercentage: 33,
        duration: '35 mins',
        warranty: '90 days warranty',
        description: 'Replace silent synchronous gear motor that rotates the glass tray for even cooking and reheating.',
        includedPoints: [
          'Synchronous drive motor installation (220V AC)',
          'Center coupler spindle & roller ring alignment',
          'Smooth silent 360-degree rotation test',
        ],
        popular: false,
        symptomTags: ['Turntable glass plate not rotating'],
        image: 'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },

  // 7. Stove
  {
    id: 'stove',
    label: 'Stove',
    group: 'other',
    title: 'Gas Stove & Cooktop Repair',
    subtitle: 'Low flame brass jet reaming, auto-ignition spark fix, gas valve leak detection & burner replacement',
    eta: '40 mins',
    rating: 4.88,
    totalBookings: '710K bookings',
    warrantyBadge: '30-Day Flame & Leak Guarantee',
    visualComponent: StoveVisual,
    commonIssues: [
      'Low yellow flame / uneven burner ring',
      'Gas smell near stove / leakage detected',
      'Auto-ignition not sparking / clicking continuously',
      'Control knob jammed or broken',
      'Glass top cooktop burner loose',
    ],
    technicianChecklist: [
      'Combustible LPG/PNG gas sniffer meter test',
      'Brass jet nozzle micro-reaming tool',
      'Soap bubble pressure seal verification',
      'Zero mess kitchen floor mat protection',
      'Flame air-to-fuel ratio optimization',
    ],
    services: [
      {
        id: 'stove-burner-low-flame-service',
        title: 'Burner Deep Cleaning & Flame Tuning',
        rating: 4.9,
        reviewsCount: '340K',
        price: 249,
        originalPrice: 399,
        discountPercentage: 37,
        duration: '30 mins',
        warranty: '30 days warranty',
        description: 'Ream micro carbon clogs out of brass gas nozzles and clean burner heads to restore crisp blue high-heat flames.',
        includedPoints: [
          'Precision brass jet pinhole reaming',
          'Burner mixing tube carbon scrub',
          'Air shutter adjustment to eliminate yellow soot',
          '30% faster cooking flame efficiency',
        ],
        popular: true,
        symptomTags: ['Low yellow flame / uneven burner ring'],
        image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'stove-gas-leakage-safety-fix',
        title: 'Gas Leakage Sniffer Audit & Valve Sealing',
        rating: 4.93,
        reviewsCount: '220K',
        price: 349,
        originalPrice: 499,
        discountPercentage: 30,
        duration: '35 mins',
        warranty: '60 days safety warranty',
        description: 'Certified safety audit testing cylinder regulator, orange Suraksha rubber hose, and internal manifold valves.',
        includedPoints: [
          'Electronic combustible gas detector leak survey',
          'Spindle valve lubrication with high-temp grease',
          'Clamp replacement with high tension stainless steel',
          'Complete household gas safety clearance report',
        ],
        popular: true,
        symptomTags: ['Gas smell near stove / leakage detected'],
        image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'stove-auto-ignition-spark-repair',
        title: 'Hob Auto-Ignition Spark & Switch Repair',
        rating: 4.84,
        reviewsCount: '130K',
        price: 399,
        originalPrice: 599,
        discountPercentage: 33,
        duration: '40 mins',
        warranty: '90 days warranty',
        description: 'Fix built-in hobs where clicking won’t ignite gas or knob clicks continuously after releasing.',
        includedPoints: [
          'Piezo/pulse generator diagnostic',
          'Ceramic spark electrode alignment and cleaning',
          'Micro-switch wiring harness replacement',
        ],
        popular: false,
        symptomTags: ['Auto-ignition not sparking / clicking continuously', 'Control knob jammed or broken'],
        image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },

  // 8. Laptop
  {
    id: 'laptop',
    label: 'Laptop',
    group: 'other',
    title: 'Laptop Repair & Hardware Service',
    subtitle: 'Doorstep certified technician for Windows & MacBook thermal clean, battery fix, display & OS speedup',
    eta: '60 mins',
    rating: 4.89,
    totalBookings: '540K bookings',
    warrantyBadge: '90-Day Hardware Warranty',
    visualComponent: LaptopVisual,
    commonIssues: [
      'Laptop overheating & fan roaring loud',
      'Laptop running slow / SSD upgrade needed',
      'Broken / flickering LCD display screen',
      'Battery draining fast / not charging',
      'Spilled liquid / keyboard keys not working',
    ],
    technicianChecklist: [
      'Arctic MX-4 premium high-conductivity thermal paste',
      'Anti-static ESD grounding wristband',
      'Precision magnetic iFixit driver toolkit',
      'Full post-repair hardware diagnostic benchmark',
      'Zero data loss privacy guarantee',
    ],
    services: [
      {
        id: 'laptop-thermal-paste-fan-service',
        title: 'Deep Thermal Cleaning & Heatsink Repasting',
        rating: 4.91,
        reviewsCount: '280K',
        price: 499,
        originalPrice: 799,
        discountPercentage: 37,
        duration: '45 mins',
        warranty: '60 days cooling warranty',
        description: 'Cool down blazing hot laptops, stop throttling and eliminate loud fan noise by replacing dry factory paste.',
        includedPoints: [
          'High thermal conductivity Arctic MX paste application',
          'Cooling fan blower impeller blade dust extraction',
          'Heatsink copper fin stack ultrasonic clearing',
          'Lowers CPU/GPU operating temperature by 15-20°C',
        ],
        popular: true,
        symptomTags: ['Laptop overheating & fan roaring loud', 'Laptop running slow / SSD upgrade needed'],
        image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'laptop-battery-charging-fix',
        title: 'Laptop Battery & DC Charging Jack Fix',
        rating: 4.86,
        reviewsCount: '140K',
        price: 599,
        originalPrice: 899,
        discountPercentage: 33,
        duration: '40 mins',
        warranty: '180 days warranty',
        description: 'Doorstep replacement for swollen batteries, rapid discharge, or loose charging sockets requiring wire bending.',
        includedPoints: [
          'OEM grade high cycle battery replacement',
          'DC power jack pin soldering / socket harness swap',
          'Charging controller motherboard circuit verification',
        ],
        popular: false,
        symptomTags: ['Battery draining fast / not charging'],
        image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'laptop-display-keyboard-replacement',
        title: 'Display Screen & Keyboard Replacement',
        rating: 4.88,
        reviewsCount: '190K',
        price: 899,
        originalPrice: 1299,
        discountPercentage: 30,
        duration: '60 mins',
        warranty: '90 days warranty',
        description: 'Doorstep swap for cracked LCD screens, vertical lines, or sticky keys damaged by liquid spills.',
        includedPoints: [
          'A+ Grade IPS high brightness display panel',
          'eDP ribbon cable testing and hinge tension check',
          'Original layout keyboard replacement with backlighting',
        ],
        popular: true,
        symptomTags: ['Broken / flickering LCD display screen', 'Spilled liquid / keyboard keys not working'],
        image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },

  // 9. RO/Water Purifier
  {
    id: 'ro-purifier',
    label: 'RO/Water Purifier',
    group: 'other',
    title: 'RO Water Purifier Service & Filter Change',
    subtitle: 'TDS meter calibration, multi-stage sediment, carbon & RO membrane replacement, booster pump repair',
    eta: '40 mins',
    rating: 4.9,
    totalBookings: '1.9M bookings',
    warrantyBadge: '1-Year Filter Longevity Guarantee',
    visualComponent: ROWaterPurifierVisual,
    commonIssues: [
      'Water tastes bad or smells funny',
      'Water flow from tap is very slow / trickling',
      'Continuous beeping / filter replacement alert',
      'Water leaking from purifier body or pipes',
      'Booster pump vibrating or making buzzing sound',
    ],
    technicianChecklist: [
      'Digital HM TDS meter water purity test (Input vs Output)',
      '100% NSF certified DOW Filmtec / Toray RO membrane',
      'High pressure food-grade push-fit John Guest fittings',
      'UV intensity lamp optical transmission check',
      'Tank sanitized with food-grade chlorine tablet',
    ],
    services: [
      {
        id: 'ro-complete-service-filter-check',
        title: 'RO Purifier Complete Service & Filter Flush',
        rating: 4.91,
        reviewsCount: '620K',
        price: 399,
        originalPrice: 599,
        discountPercentage: 33,
        duration: '35 mins',
        warranty: '30 days warranty',
        description: 'Comprehensive digital TDS check, sediment pre-filter clean, and booster pump pressure calibration.',
        includedPoints: [
          'Digital TDS test of raw inlet vs pure drinking water',
          'Pre-filter bowl cleaning & spun candle flush',
          'Booster pump output pressure verification (80+ PSI)',
          'Storage tank antibacterial sanitization',
        ],
        popular: true,
        symptomTags: ['Water tastes bad or smells funny', 'Water flow from tap is very slow / trickling'],
        image: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'ro-membrane-all-filters-kit',
        title: 'Complete Filter Replacement Kit (Sediment + Carbon + RO)',
        rating: 4.92,
        reviewsCount: '380K',
        price: 1899,
        originalPrice: 2499,
        discountPercentage: 24,
        duration: '50 mins',
        warranty: '1-Year Filter Life Guarantee',
        description: 'Replaces all 4 core filtration cartridges to restore sweet tasting 100% safe drinking water.',
        includedPoints: [
          'High iodine coconut shell activated carbon block',
          '5-micron polypropylene spun sediment filter',
          'Genuine 80 GPD thin-film composite RO membrane',
          'Post-carbon mineralizer cartridge for essential minerals',
        ],
        popular: true,
        symptomTags: ['Continuous beeping / filter replacement alert', 'Water tastes bad or smells funny'],
        image: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'ro-booster-pump-leak-repair',
        title: 'Booster Pump & Leakage Repair',
        rating: 4.86,
        reviewsCount: '190K',
        price: 699,
        originalPrice: 999,
        discountPercentage: 30,
        duration: '40 mins',
        warranty: '90 days warranty',
        description: 'Replace noisy vibrating pumps or fix cracked push-fit elbow joints causing water puddles.',
        includedPoints: [
          'Heavy duty copper winding 24V DC booster pump',
          'Auto cut-off high pressure / low pressure switch setup',
          'Leak-proof push-in quick connect collet replacement',
        ],
        popular: false,
        symptomTags: ['Booster pump vibrating or making buzzing sound', 'Water leaking from purifier body or pipes'],
        image: 'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },

  // 10. Geyser
  {
    id: 'geyser',
    label: 'Geyser',
    group: 'other',
    title: 'Geyser & Water Heater Repair',
    subtitle: 'Instant & storage geyser heating element replacement, thermostat auto-cut fix, tank descaling & plumbing repair',
    eta: '45 mins',
    rating: 4.87,
    totalBookings: '1.2M bookings',
    warrantyBadge: '1-Year Heating Element Guarantee',
    visualComponent: GeyserVisual,
    commonIssues: [
      'Water not getting hot / takes too long',
      'Geyser trips electricity / MCB immediately',
      'Water leaking from bottom or inlet pipe',
      'Overheating / steam coming from tap',
      'Rust-colored water or strange sizzling noise',
    ],
    technicianChecklist: [
      'Digital insulation megohmmeter earth leakage test',
      'ISI marked copper/incoloy heavy heating coil',
      'High sensitivity stem thermostat auto-cut check',
      'Tank sediment and calcium scale flush',
      'Pressure relief safety valve (PRV) testing',
    ],
    services: [
      {
        id: 'geyser-heating-element-coil-fix',
        title: 'Heating Element & Thermostat Replacement',
        rating: 4.89,
        reviewsCount: '480K',
        price: 699,
        originalPrice: 999,
        discountPercentage: 30,
        duration: '45 mins',
        warranty: '1-Year Warranty',
        description: 'Solve no hot water or tripping circuit breakers by installing a genuine copper/incoloy heating element.',
        includedPoints: [
          'Heavy duty 2000W / 3000W ISI certified heating element',
          'Dual thermostat & thermal cut-out safety calibration',
          'Silicone tank flange gasket replacement to prevent leaks',
          'Water heating verified within 10 minutes',
        ],
        popular: true,
        symptomTags: ['Water not getting hot / takes too long', 'Geyser trips electricity / MCB immediately'],
        image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'geyser-tank-descaling-sediment-wash',
        title: 'Tank Hard-Water Descaling & Calcium Flush',
        rating: 4.86,
        reviewsCount: '260K',
        price: 449,
        originalPrice: 649,
        discountPercentage: 30,
        duration: '40 mins',
        warranty: '30 days warranty',
        description: 'Flush out rock-hard calcium limestone deposits and rust flakes to restore tank capacity and heating speed.',
        includedPoints: [
          'Chemical flush of stainless steel / glass-lined inner tank',
          'Magnesium sacrificial anode rod inspection',
          'Eliminates strange boiling sizzling noises',
          'Restores 25% faster water heating speed',
        ],
        popular: true,
        symptomTags: ['Rust-colored water or strange sizzling noise', 'Water not getting hot / takes too long'],
        image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'geyser-pipe-leakage-valve-fix',
        title: 'Pipe Leakage & Safety Pressure Relief Valve Fix',
        rating: 4.84,
        reviewsCount: '180K',
        price: 399,
        originalPrice: 599,
        discountPercentage: 33,
        duration: '35 mins',
        warranty: '90 days warranty',
        description: 'Stop continuous water dripping from inlet/outlet braided connection pipes or multi-function safety valves.',
        includedPoints: [
          'High burst pressure multi-function valve (MFV) install',
          'SS 304 braided flexible connector hose tightening',
          'Teflon tape high pressure sealing on brass nipples',
        ],
        popular: false,
        symptomTags: ['Water leaking from bottom or inlet pipe', 'Overheating / steam coming from tap'],
        image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },

  // 11. Air Cooler
  {
    id: 'air-cooler',
    label: 'Air Cooler',
    group: 'other',
    title: 'Air Cooler Service & Repair',
    subtitle: 'Honeycomb cooling pad change, submersible pump fix, fan motor repair & anti-mosquito sanitization',
    eta: '45 mins',
    rating: 4.85,
    totalBookings: '650K bookings',
    warrantyBadge: '60-Day Summer Chill Guarantee',
    visualComponent: AirCoolerVisual,
    commonIssues: [
      'Cooler blowing warm air / pump not pumping water',
      'Musty stale odor / mold on cooling pads',
      'Fan motor humming but blades not spinning',
      'Water leaking from tank or drain plug',
      'Loud squeaking / oscillating louvers stuck',
    ],
    technicianChecklist: [
      'High-discharge submersible water pump test',
      'High density anti-bacterial honeycomb pad fit',
      'Blower fan shaft lubrication & capacitor check',
      'Tank deep scrub with anti-mosquito larvicide',
      'Full electrical wiring & earth continuity audit',
    ],
    services: [
      {
        id: 'cooler-water-pump-motor-fix',
        title: 'Water Submersible Pump & Wiring Replacement',
        rating: 4.88,
        reviewsCount: '290K',
        price: 399,
        originalPrice: 599,
        discountPercentage: 33,
        duration: '35 mins',
        warranty: '90 days warranty',
        description: 'Fixes coolers blowing warm dry air due to dead or choked submersible water pumps.',
        includedPoints: [
          'Heavy duty copper submersible water pump installation',
          'Water distributor pipe clearing & uniform pad wetting',
          'Safe insulated wiring connectors',
          'Instant cool airflow restoration',
        ],
        popular: true,
        symptomTags: ['Cooler blowing warm air / pump not pumping water'],
        image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cooler-honeycomb-pad-replacement',
        title: 'Honeycomb Cooling Pad Replacement & Descaling',
        rating: 4.87,
        reviewsCount: '210K',
        price: 549,
        originalPrice: 799,
        discountPercentage: 31,
        duration: '45 mins',
        warranty: '60 days freshness warranty',
        description: 'Replace salt-encrusted or foul-smelling pads with high-density cellulose honeycomb pads for 3x cooler air.',
        includedPoints: [
          'High water-retention thick cellulose honeycomb pads',
          'Pre-fitted plastic side frame bracket alignment',
          'Tank pressure wash and anti-fungal treatment',
          'Eliminates sour damp odor instantly',
        ],
        popular: true,
        symptomTags: ['Musty stale odor / mold on cooling pads', 'Cooler blowing warm air / pump not pumping water'],
        image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cooler-fan-motor-speed-repair',
        title: 'Fan Motor Bush & Speed Capacitor Repair',
        rating: 4.83,
        reviewsCount: '150K',
        price: 499,
        originalPrice: 699,
        discountPercentage: 28,
        duration: '40 mins',
        warranty: '90 days warranty',
        description: 'Restore 3-speed fan blower operation, replace burned run capacitors or free seized bronze motor bushings.',
        includedPoints: [
          'High grade motor run capacitor replacement',
          'Synthetic high-temp bronze bush shaft lubrication',
          'Blade balancing to prevent shaking and humming',
        ],
        popular: false,
        symptomTags: ['Fan motor humming but blades not spinning', 'Loud squeaking / oscillating louvers stuck'],
        image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },
];
